name: Test Workflow
on:
  workflow_dispatch: {}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@vt

      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.3.26
      
