name: "Test 1"
 
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
 workflow_dispatch: {}
 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for the Terraform state
 #BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
 
jobs:
  call-reusable-terraform-workflow:
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      var-file: "./organizations/org-1.tfvars"
    secrets: inherit
