name: Test Workflow
on:
  workflow_dispatch: {}

jobs:
  build-and-push-image:
    runs-on: github-runners
    permissions:
      contents: read
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-app
          tags: latest v1.0
          containerfiles: ./Dockerfile
