name: Test Workflow
on:
  workflow_dispatch: {}

jobs:
  build-and-push-image:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    permissions:
      contents: read
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build image  
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: test-image/testing:latest
