name: "Test 1"
 
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
 workflow_dispatch: {}
  
jobs:
  call-reusable-terraform-workflow:
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      var-file: "$GITHUB_WORKSPACE/organizations/org-1.tfvars"
    secrets: inherit
