name: "test-org-1-terraform"
run-name: Update test-org-1 started by @${{ github.actor }}
 
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
   - test-org-1/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
   - test-org-1/**
 workflow_dispatch: {}
  
jobs:
  call-reusable-terraform-workflow:
    uses: ./.github/workflows/terraform-reusable-workflow.yaml
    with:
      var-file: "$GITHUB_WORKSPACE/test-org-1/terraform.tfvars"
    secrets: inherit
